apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort   # trong minikube nên dùng NodePort
  selector:
    app: inventory-app
  ports:
    - protocol: TCP
      port: 8000        # cổng service
      targetPort: 8000  # cổng container
      nodePort: 30007   # cổng để truy cập từ localhost
